export const data=[
    {
        id:1,
        name:"Kathakali",
        img1:"https://i.pinimg.com/236x/5b/0d/88/5b0d88caf2f8cd74418cb5d71fa0174c.jpg",
        images:"https://i.pinimg.com/236x/65/5c/dd/655cddd04b465d184653ebfe2b728e11.jpg",
        description:"Kathakali is a classical dance form of Kerala, demanding long years of training. Believed to have evolved from Ramanattam, another classical art form composed by Kottarakkara Thampuran, Kathakali incorporates the techniques of some of the major ritual art forms of Kerala.",
        detail:"Famous around the world, Kathakali's magnificence has won great admiration for the state of Kerala. Proud that this renowned artfrom originated, was originated from Keralaâ€™s shores over 300 years ago. It combines devotion, drama, dance, music, costumes and make up into a divine experience for all who get to view it. It retells the great stories of the past, mostly from Indian epics, and leaves one spellbound at the various intricacies involved in the performance. Every single quiver of the lips, flicker of the eyes or a movement involving the fingers twirling, has great significance. The entire performance sees the audience unable to take their eyes away from the spectacle taking place on stage.",        
    
    },
    {
     id: 2,
        name:"Bharatanatyam",
        images:"https://i.pinimg.com/236x/19/9f/5c/199f5c5c98d7f3ec99e49dc863ee2552.jpg",
        img1:"https://i.pinimg.com/236x/f8/07/13/f80713784de44120f4b020ab7bcb1fed.jpg",
        description:"Bharatanatyam is one of the most popular and widely practiced classical dance styles of India, with sculptural evidence dating back nearly 3000 years. A highly spiritual and dedicatory dance form, Bharatanatyam's roots go back to the Hindu temples of Tamil Nadu, in South India.",
        detail:"Bharatanatyam, a pre-eminent Indian classical dance form presumably the oldest classical dance heritage of India is regarded as mother of many other Indian classical dance forms. Conventionally a solo dance performed only by women, it initiated in the Hindu temples of Tamil Nadu and eventually flourished in South India. Theoretical base of this form traces back to 'Natya Shastra', the ancient Sanskrit Hindu text on the performing arts. A form of illustrative anecdote of Hindu religious themes and spiritual ideas emoted by dancer with excellent footwork and impressive gestures its performance repertoire includes nrita, nritya and natya. Accompanists include a singer, music and particularly the guru who directs and conducts the performance. It also continues to inspire several art forms including paintings and sculptures starting from the spectacular 6th to 9th century CE temple sculptures.",
    },
    {
     id: 3,
        name:"Kathak",
        img1:"https://i.pinimg.com/564x/db/26/05/db2605531ccc7902672b6b0905292f4e.jpg",
        images:"https://i.pinimg.com/564x/26/cf/3f/26cf3f0b72b0c22ced887a90728bc326.jpg",
        description:"Kathak is one of the main genres of ancient Indian classical dance and is traditionally regarded to have originated from the travelling bards of North India referred as Kathakars or storytellers. These Kathakars wandered around and communicated legendary stories via music, dance and songs quite like the early Greek theatre. The genre developed during the Bhakti movement, the trend of theistic devotion which evolved in medieval Hinduism.",
        detail:"Kathak is one of the main genres of ancient Indian classical dance and is traditionally regarded to have originated from the travelling bards of North India referred as Kathakars or storytellers. These Kathakars wandered around and communicated legendary stories via music, dance and songs quite like the early Greek theatre. The genre developed during the Bhakti movement, the trend of theistic devotion which evolved in medieval Hinduism. The Kathakars communicate stories through rhythmic foot movements, hand gestures, facial expressions and eye work. This performing art that incorporates legends from ancient mythology and great Indian epics, especially from the life of Lord Krishna became quite popular in the courts of North Indian kingdoms. Three specific forms of this genre that is three gharanas (schools), which mostly differ in emphasis given to footwork versus acting, are more famous namely, the Jaipur gharana, the Benaras gharana and the Lucknow gharana.",
    },
    {
     id: 4,
        name:"Kuchipudi",
        img1:"https://in.pinterest.com/pin/2744449762456448/",
        images:"https://i.pinimg.com/564x/84/02/7d/84027d84a89b90f7d998337a6a09f0fc.jpg",
        description:"Kuchipudi is one of the classical styles of Indian dance. Around the third and fourth decade of this century it emerged out of a long rich tradition of dance-drama of the same name.",
        detail:"Kuchipudi, a pre-eminent Indian classical dance form counted among ten leading classical dance forms of India, is a dance-drama performance art that originated in a village of Krishna district of Andhra Pradesh, India. Similar to all leading Indian classical dance forms, Kuchipudi too evolved as a religious art rooting back to the age-old Hindu Sanskrit text 'Natya Shastra' and connects traditionally with temples, spiritual faiths and travelling bards. This ancient dance form finds place in the 10th century copper inscriptions and in 15th century texts like 'Machupalli Kaifat'. Traditionally it is regarded that the sanyassin of Advaita Vedanta sect, Tirtha Narayana Yati, and his disciple Siddhendra Yogi initiated, methodized and arranged the present day version of the dance form in 17th century. Usually performance repertoire of Kuchipudi that is broadly oriented on Lord Krishna and the tradition of Vaishnavism include an invocation, dharavu - short dance, nritta - pure dance and nritya - expressive dance respectively.",
    },
    {
        id: 5,
        name:"Odissi",
        img1:"https://i.pinimg.com/564x/f3/bd/cc/f3bdcc48cdc65902ff1aa6cfbe305a78.jpg",
        images:"https://i.pinimg.com/236x/ad/ec/a8/adeca897bfb311f87957b094b4c68fc3.jpg",
        description:"Odissi is traditionally a dance-drama genre of performance art, where the artist(s) and musicians play out a story, a spiritual message or devotional poem from the Hindu texts, using symbolic costumes, body movement, abhinaya (expressions) and mudras (gestures and sign language) set out in ancient Sanskrit literature.",
        detail:"Odissi or Orissi is one of the pre-eminent classical dance forms of India which originated in the Hindu temples of the eastern coastal state of Odisha in India. Its theoretical base trace back to 'Natya Shastra', the ancient Sanskrit Hindu text on the performing arts. Age-old tradition of Odissi is manifested from Odisha Hindu temples and various sites of archaeological significance that are associated with Hinduism, Jainism and Buddhism, the sculptures of which adorn dance postures of this art form. A form of illustrative anecdote of mythical and religious stories, devotional poems and spiritual ideas emoted by dancer with excellent body movements, expressions, impressive gestures and sign languages, its performance repertoire includes invocation, nrita, nritya, natya, and moksha. This dance form includes themes from Vaishnavism and others associated with Hindu gods and goddesses like Shiva, Surya and Shakti.",
    },
    {
     id: 6,
     img1:"https://i.pinimg.com/564x/a1/db/9a/a1db9a68fed438b14ec9be6cab985dee.jpg",
        name:"Manipuri",
        images:"https://i.pinimg.com/736x/25/4c/e1/254ce17121de8db3e916585b7fe9fdba.jpg",
        description:"Manipuri is one of such India's most prominent classical dance forms widely popular in its rich North East culture and traditions. Known for its elements of Hindu shastras such Vaishnavism, Radha-Krishna bhakti and Nataraja Natyam, Manipuri is known to be one of the greatest symbols of Bhakti Rasa.",
        detail:"Manipuri dance is counted among major classical dance forms of India, especially noted for themes based on Vaishnavism and spectacular execution of 'Ras Lila', dance dramas based on love between Radha and Krishna. Other themes included in this art form associate with Shaktism, Shaivism and on the sylvan deities called Umang Lai during Manipuri festival 'Lai Haraoba'. This dance form is named after the north-eastern state of Manipur, India from where it originated but it has its roots in 'Natya Shastra', the age-old Sanskrit Hindu text. A mix of Indian and southeast Asian culture is palpable in this form. The age-old dance tradition of the place is manifested from great Indian epics, 'Ramayana' and 'Mahabharata', where the native dance experts of Manipur are referred as 'Gandharvas'. The Manipuris perform this religious art that aims at expressing spiritual values during Hindu festivals and other important cultural occasions like marriage.",
    },
    {
     id: 7,
     img:"https://i.pinimg.com/236x/bf/96/f4/bf96f4d2edce7bedeb20645e76e0f60a.jpg",
        name:"Mohiniyattam",
        images:"https://i.pinimg.com/564x/3d/8a/24/3d8a24d3ee6f5b43c12c2addc39da768.jpg",
        description:"Mohiniyattam (Mohiniattam) is a classical dance form of Kerala in South India. The origin and popularity of this dance form is closely tagged to the great Tamil dance master Vadivelu, one of the Thanjavur quartets. One among the eight Indian classical dance forms, Mohiniyattam is a graceful dance to watch and is a solo recital by women.",
        detail:"Mohiniattam or Mohiniyattam is an Indian classical dance form that evolved in the state of Kerala, India, and is counted among the two popular dance arts of the state, the other being Kathakali. Although its roots date back to the age-old Sanskrit Hindu text on performing arts called 'Natya Shastra', similar to other Indian classical dance forms, Mohiniattam adheres to the Lasya type that showcases a more graceful, gentle and feminine form of dancing. Mohiniattam derives its name from the word 'Mohini', a female avatar of Lord Vishnu. Conventionally a solo dance performed by female artists, it emotes a play through dancing and singing where the song is customarily in Manipravala which is a mix of Sanskrit and Malayalam language and the recitation may be either performed by the dancer herself or by a vocalist with the music style being Carnatic.",
    },
    {
     id: 8,
        name:"Sattriya",
        img1:"https://i.pinimg.com/236x/fe/32/1c/fe321c07900b4f5c59ce98a7188a3eac.jpg",
        images:"https://i.pinimg.com/236x/78/86/34/788634f5467b200002419aedd6cfeeee.jpg",
        description:"Sattriya Dance has its origin in the 'Sattriyas' established by Mahapurush Srimanta Sankardev in the 15th and the 16th century. The Sattras were established for the propagation of Vaishnavism and later they became the religious, cultural and social hub for the people of Assam. The great Vaishnavite Saint has developed this dance form with its basic roots aligned with the characteristics of other forms of Indian classical dance.",
        detail:"Sattriya Dance has its origin in the 'Sattriyas' established by Mahapurush Srimanta Sankardev in the 15th and the 16th century. The Sattras were established for the propagation of Vaishnavism and later they became the religious, cultural and social hub for the people of Assam. The great Vaishnavite Saint has developed this dance form with its basic roots aligned with the characteristics of other forms of Indian classical dance. Initially a part of the 'Ankia Naats', this dance form derived its name from the word 'Sattriyas' .This dance form was originally performed in the Sattras and the Namghars by the male Bhokots as a part of religious rituals and for spreading the philosophy of Vaishnavism and was confined within the four walls of the sattras for several centuries.",
    },
    {
     id: 9,
        name:"Kalaripayattu",
        img1:"https://i.pinimg.com/236x/bc/0b/d5/bc0bd52581655c70ae3662745fea1df9.jpg",
        images:"https://www.keralatourism.org/images/artforms/large/kalaripayattu20131111114353_27_1.jpg",
        description:"Kalaripayattu is the martial art form of Kerala. Kalaripayattu's influence can be seen in most of the art forms of Kerala. In the past kalaris (combat arena or battle field) formed an integral part of the lives of the people. Without any gender discrimination boys and girls in their childhood would be sent to the Kalaris for practicing. With social life undergoing changes, the position of Kalaris and their influence changed.",
        detail:"Kalaripayattu is the martial art form of Kerala. Kalaripayattu's influence can be seen in most of the art forms of Kerala. In the past kalaris (combat arena or battle field) formed an integral part of the lives of the people. Without any gender discrimination boys and girls in their childhood would be sent to the Kalaris for practicing. With social life undergoing changes, the position of Kalaris and their influence changed. Today, Kalaripayattu is staged during festivals and other occasions as a showpiece. People are more interested in kalari treatment (as a system of medicine) and Marmachikitsa (treatment of vital parts).",
    },
    {
     id: 10,
        img1:"https://i.pinimg.com/236x/e1/7a/8e/e17a8eb7c5edccdd30f1ad839289bde1.jpg",
        name:"Kalamezhuthu Art",
        images:"https://i.pinimg.com/564x/e1/7a/8e/e17a8eb7c5edccdd30f1ad839289bde1.jpg",
        description:"Kalamezhuthu is a traditional art form that originated in Kerala. The art form uses the patterns of rice flour paste and water colours on a cloth to create elaborate paintings. The whole process of Kalamezhuthu is done by using the hands only and it cannot be erased or reused, which makes it an exclusive and exquisite art form.",
        detail:"Kalamezhuthu is a type of medieval Hindu art that was popular in the south of India from around 1750-1850. The word means 'drawing pictures', and pictures of gods and goddesses became the central theme. A lot of religious art is done in the form of ritualistic drawings for example, pictures of gods created by using coloured powders. It is believed that such depictions are there to 'welcome' gods. The art form is accompanied by a long chant sung before the performance starts. It's done on the floor, which is what gives it its meaning in this context. The artform sees all of Earth as one large canvas to paint on.Kalamkari use natural colors from materials such as charcoal, turmeric, leaves and rice. White is derived from rice, black from charcoal, yellow from turmeric and green from leaves. Red can be made by mixing other colors. During November & December, you can see Kalamezhuthu performances at many different Devi temples in Kerala. The maestros use coloured powder to create beautiful drawings of the Gods on the floor. Some of them include Bhadrakaali, Ayyappan, Serpent or Vettakkorumakan.",
    }
    
]